name: Build VRCXPlus

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release

      - name: Publish application
        run: dotnet publish --configuration Release --output ./bin/Release/net8.0/win-x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VRCXPlus
          path: bin/Release/net8.0/win-x64/VRCXPlus.exe
